# Generated by Django 3.1.7 on 2021-05-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_Info',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(db_column='First Name', max_length=20, verbose_name='fname')),
            ],
        ),
    ]
