# Generated by Django 3.2.3 on 2021-05-21 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_Info',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(db_column='First Name', max_length=20)),
                ('Last_Name', models.CharField(db_column='Last Name', max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(db_column='password', max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Student Information',
            },
        ),
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gitLink', models.URLField(verbose_name='GitHub Link')),
                ('profile_pic', models.ImageField(upload_to='profilePic')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student_Activities.student_info')),
            ],
            options={
                'verbose_name_plural': 'Portfolio Details',
            },
        ),
    ]
