# Generated by Django 3.1.7 on 2021-05-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_Activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='First_Name',
            field=models.CharField(db_column='First Name', max_length=20),
        ),
    ]
