# Generated by Django 3.2.3 on 2021-05-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_Activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='gitLink',
            field=models.URLField(blank=True, verbose_name='GitHub Link'),
        ),
    ]
