# Generated by Django 3.1.7 on 2021-05-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_Activities', '0003_student_info_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_info',
            name='Email',
            field=models.EmailField(default='dsdS', max_length=254),
            preserve_default=False,
        ),
    ]
