# Generated by Django 3.1.7 on 2021-05-16 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_Activities', '0005_student_info_my_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_info',
            name='my_choice',
        ),
    ]
