# Generated by Django 3.1.7 on 2021-05-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_Activities', '0006_remove_student_info_my_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_info',
            name='mychoice',
            field=models.CharField(choices=[('GOLD', 'Gold'), ('SILVER', 'Silver'), ('BRONZE', 'Bronze')], default='fd', max_length=20),
            preserve_default=False,
        ),
    ]
