# Generated by Django 3.1.7 on 2021-05-17 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_Activities', '0007_student_info_mychoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_info',
            name='mychoice',
        ),
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gitLink', models.URLField(db_column='Git Link')),
                ('profile_pic', models.ImageField(upload_to='profilePic')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student_Activities.student_info')),
            ],
        ),
    ]
