# Generated by Django 3.1.7 on 2021-05-17 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_Activities', '0008_auto_20210517_1303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student_info',
            options={'verbose_name_plural': 'Student Information'},
        ),
    ]
